# -*- coding: utf-8 -*-
"""Weather-Data-Analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WXerxoqOw7fuNghJMVq0ybnIAByyy94Z
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

filename = 'weather.xlsx'
search_path = '/content/weather.xlsx'

# Load the XLSX file into a DataFrame
dataset = pd.read_excel('/content/weather.xlsx')

dataset.shape
dataset.head()

display(dataset)

print(dataset.describe())

dataset.plot(x='MinTemp', y='MaxTemp' , style='o')
plt.title('min vs max')
plt.xlabel('mintemp')
plt.ylabel('maxtemp')
plt.show()

plt.figure(figsize=(15,10))
plt.tight_layout()
seaborn.distplot(dataset['MaxTemp'])
plt.show()

X= dataset['MinTemp'].values.reshape(-1,1)
y= dataset['MaxTemp'].values.reshape(-1,1)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=0)

model =LinearRegression()
model.fit(X_train,y_train)

print('Intercept is :',model.intercept_)

print('Coefficient is :' ,model.coef_)

y_pred= model.predict(X_test)

df=  pd.DataFrame({'Actual': y_test.flatten(), 'Predicted': y_pred.flatten()})
print(df)

df1= df.head(50)
df1.plot(kind='bar', figsize=(10,5))
plt.grid(which='major', linestyle='-',linewidth='0.5', color='blue')
plt.grid(which='minor', linestyle=':',linewidth='0.5', color='black')
plt.show()

plt.scatter(X_test,y_test,color='red')
plt.plot(X_test,y_pred,color='black',linewidth=2)
plt.show()

print('Mean abolute error is:', metrics.mean_absolute_error(y_test,y_pred))
print('Mean squared error is:', metrics.mean_squared_error(y_test,y_pred))
print('Root mean squared error is:', np.sqrt(metrics.mean_squared_error(y_test,y_pred)))